package com.alibaba.webx.tutorial1.app1;

public class Visitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.id
     *
     * @mbg.generated Sat Oct 08 15:20:02 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.name
     *
     * @mbg.generated Sat Oct 08 15:20:02 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.id
     *
     * @return the value of visitor.id
     *
     * @mbg.generated Sat Oct 08 15:20:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.id
     *
     * @param id the value for visitor.id
     *
     * @mbg.generated Sat Oct 08 15:20:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.name
     *
     * @return the value of visitor.name
     *
     * @mbg.generated Sat Oct 08 15:20:02 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.name
     *
     * @param name the value for visitor.name
     *
     * @mbg.generated Sat Oct 08 15:20:02 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}